### ISSUE TITLE
Windows and my Firewall block installing

### ISSUE THREAD

**Issue by Camos101** [deffcolony/rvc-easy-menu#1]
I've turned them off, placed exception lists and it still get's blocked as though a virus.
I hope it's not really a virus.

**Comment by deffcolony** [comment]
@Camos101 The program may trigger a firewall popup asking if you want to allow the Python connection. This can happen because the program is designed to be used over a local area network (inside your house only), and firewalls may request your permission to connect or block it.

I understand your concern, but I can assure you that it's not a virus. What you're experiencing might be due to firewall settings, which can sometimes be a bit overzealous. you can safely allow the connection

Can you please provide me the screenshot of the message you get?
